spring:
  datasource:
    url: jdbc:mysql://localhost:3306/longurl?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 150
      idle-timeout: 10000
      pool-name: HikariCPPoolName
      max-lifetime: 1800000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
